### ISSUE TITLE
Garbage character when setting completeopt=noinsert,noselect

### ISSUE THREAD

**Issue by renstrom** [davidhalter/jedi-vim#667]
### Issue

Jedi-vim produces garbage `0` after "dot completion" characters if `completeopt` contains either `noselect` or `noinsert`.

### Steps to reproduce

![asciicast](https://cloud.githubusercontent.com/assets/177685/22460439/2497d468-e7a5-11e6-8bb6-ae3d491603bd.gif)

### Versions

 - jedi-vim: 52772e171f0ea010c7e91e81d4db3a5b454976cd
 - Vim / Neovim: Vim 8.0.271 and Neovim v0.2.0-485-g81525dc5
 - Python: 2.7.13 in Vim and 3.6.0 and 2.7.13 in Neovim

### Output of the "JediDebugInfo" command (in a Python buffer)

```
#### Jedi-vim debug information
Using Python version: 2
 - sys.version: 2.7.13 (default, Dec 18 2016, 07:03:39), [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang
-800.0.42.1)]
 - site module: /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7
/site.pyc
Jedi path: /Users/peter/.vim/plugged/jedi-vim/jedi/jedi/__init__.py
 - version: 0.10.0
 - sys_path:
    - /Users/peter/.vim/plugged/jedi-vim
    - /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python27.zip
    - /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7
    - /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darw
in
    - /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
    - /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/
lib-scriptpackages
    - /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
    - /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old
    - /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynlo
ad
    - /Users/peter/Library/Python/2.7/lib/python/site-packages
    - /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-pack
ages
    - _vim_path_
jedi-vim git version: 52772e1
jedi git submodule status:  f05c0714c701ab784bd344aa063acd216fb45ec0 jedi (v0.9.0-550-gf05c0714)

##### Settings
```
```
```

### Output of the "messages" Vim command

```
 - sys.version: 2.7.13 (default, Dec 18 2016, 07:03:39), [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang
-800.0.42.1)]
 - site module: /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7
/site.pyc
Jedi path: /Users/peter/.vim/plugged/jedi-vim/jedi/jedi/__init__.py
 - version: 0.10.0
 - sys_path:
    - /Users/peter/.vim/plugged/jedi-vim
    - /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python27.zip
    - /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7
    - /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darw
in
    - /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
    - /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/
lib-scriptpackages
    - /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
    - /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old
    - /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynlo
ad
    - /Users/peter/Library/Python/2.7/lib/python/site-packages
    - /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-pack
ages
    - _vim_path_
```

### Output of "scriptnames" Vim command

```
  1: ~/Desktop/vimrc
  2: ~/.vim/autoload/plug.vim
  3: /usr/local/Cellar/vim/8.0.0271/share/vim/vim80/filetype.vim
  4: /usr/local/Cellar/vim/8.0.0271/share/vim/vim80/ftplugin.vim
  5: /usr/local/Cellar/vim/8.0.0271/share/vim/vim80/indent.vim
  6: /usr/local/Cellar/vim/8.0.0271/share/vim/vim80/syntax/syntax.vim
  7: /usr/local/Cellar/vim/8.0.0271/share/vim/vim80/syntax/synload.vim
  8: /usr/local/Cellar/vim/8.0.0271/share/vim/vim80/syntax/syncolor.vim
  9: ~/.vim/plugged/jedi-vim/plugin/jedi.vim
 10: /usr/local/Cellar/vim/8.0.0271/share/vim/vim80/plugin/getscriptPlugin.vim
 11: /usr/local/Cellar/vim/8.0.0271/share/vim/vim80/plugin/gzip.vim
 12: /usr/local/Cellar/vim/8.0.0271/share/vim/vim80/plugin/logiPat.vim
 13: /usr/local/Cellar/vim/8.0.0271/share/vim/vim80/plugin/manpager.vim
 14: /usr/local/Cellar/vim/8.0.0271/share/vim/vim80/plugin/matchparen.vim
 15: /usr/local/Cellar/vim/8.0.0271/share/vim/vim80/plugin/netrwPlugin.vim
 16: /usr/local/Cellar/vim/8.0.0271/share/vim/vim80/plugin/rrhelper.vim
 17: /usr/local/Cellar/vim/8.0.0271/share/vim/vim80/plugin/spellfile.vim
 18: /usr/local/Cellar/vim/8.0.0271/share/vim/vim80/plugin/tarPlugin.vim
 19: /usr/local/Cellar/vim/8.0.0271/share/vim/vim80/plugin/tohtml.vim
 20: /usr/local/Cellar/vim/8.0.0271/share/vim/vim80/plugin/vimballPlugin.vim
 21: /usr/local/Cellar/vim/8.0.0271/share/vim/vim80/plugin/zipPlugin.vim
 22: ~/.vim/plugged/jedi-vim/ftplugin/python/jedi.vim
 23: ~/.vim/plugged/jedi-vim/autoload/jedi.vim
 24: /usr/local/Cellar/vim/8.0.0271/share/vim/vim80/ftplugin/python.vim
 25: ~/.vim/plugged/jedi-vim/after/ftplugin/python/jedi.vim
 26: /usr/local/Cellar/vim/8.0.0271/share/vim/vim80/indent/python.vim
 27: /usr/local/Cellar/vim/8.0.0271/share/vim/vim80/syntax/python.vim
 28: ~/.vim/plugged/jedi-vim/after/syntax/python.vim
 29: ~/.vim/after/syntax/python.vim
```
